### ISSUE TITLE
ERROR: Updates were rejected because the tip of your current branch is behind

### ISSUE THREAD

**Issue by jj358mhz** [stevejenkins/pihole-cloudsync#21]
Hi @stevejenkins 

Has anyone run into this error?

root@raspberrypi-hole1:/usr/local/bin/pihole-cloudsync# ./pihole-cloudsync --push
--push option detected. Running in Push/Upload mode.
Local Pi-hole lists are different than remote Git repo. Updating remote repo...
To github.com:REDACTED/my-pihole-lists.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'git@github.com:REDACTED/my-pihole-lists.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Done!

**Comment by ThomasHedden** [comment]
I had this error on my own repository when I made a local commit and tried to push it. I am 99.999% sure that I didn't make any changes to the remote repository (on github.com).
