### ISSUE TITLE
push credentials with 2FA does not work

### ISSUE THREAD

**Issue by bondskin** [stevejenkins/pihole-cloudsync#9]
I entered username/email and password correctly but getting error message

fatal: Authentication failed for 'https://github.com/xxx/my-pihole-lists.git/'

Is this because I have 2FA activated on GitHub?
Any workaround?

thx
Mike

**Comment by roadrailer** [comment]
access token works for me

[Help docs here](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)

**Comment by bondskin** [comment]
that worked!
